Feature clean architecture
trishaagaba/Github-User-App pull request #3
Opened 2024-07-18 14:19 UTC by trishaagaba

**What does this PR do**
-Implements the clean architecture in the code
-Adds the Splash screen
-Implements the filter widget

**Things to do**
-Introduce pagination to my list
-Document the ReadMe

2024-07-18 17:20 UTC, NabunyaLilian commented on lib/features/user_lists/presentation/providers/user_provider.dart
At this point you shouldn't be communicating with the Datasource. This is the point where usecases come in

2024-07-18 17:26 UTC, NabunyaLilian commented on lib/features/user_lists/presentation/screens/home.dart
This is good work, but i suggest you break the widget into smaller widgets . let the file not exceed 200 lines of code

2024-07-18 17:30 UTC, NabunyaLilian commented on lib/features/user_profile/presentation/screens/user_profile_page.dart
fetchUserDetails method should not be in the widget

2024-07-18 17:33 UTC, trishaagaba commented on lib/features/user_lists/presentation/providers/user_provider.dart
alright let me look into it. Thank you

2024-07-18 17:35 UTC, trishaagaba commented on lib/features/user_profile/presentation/screens/user_profile_page.dart
Alright let me clean up that feature

2024-07-18 17:35 UTC, trishaagaba commented on lib/features/user_lists/presentation/screens/home.dart
Alright thank you

2024-07-23 09:22 UTC, NabunyaLilian requested changes
Good work 👍 Trisha , just make a few adjustments on the changes i've requested and then we are good to go.

2024-07-23 09:22 UTC, NabunyaLilian commented on lib/features/user_lists/data/datasources/remote/data_source.dart
Theres's some confusion here regarding the url, please clear it up. Also at this point we deal with models not entities.

2024-07-23 09:22 UTC, NabunyaLilian commented on lib/features/user_lists/data/repository/user_repository_impl.dart
This is the point where you do the conversion from a model object to an entity

2024-07-23 09:22 UTC, NabunyaLilian commented on lib/features/user_lists/presentation/providers/user_provider.dart
Look into this  "if (_isLoading) return;", what's it's significance

2024-07-23 09:22 UTC, NabunyaLilian commented on lib/features/user_profile/data/datasources/details_source.dart
At this point , we don't interact with entities, it's supposed to be models.

2024-07-23 09:22 UTC, NabunyaLilian commented on lib/features/user_profile/data/repository/userprofile_rep_imp.dart
Use class names that are easy to understand

2024-07-23 09:22 UTC, NabunyaLilian commented on lib/features/user_profile/presentation/widget/buildContent.dart
you could extract this into a helper function file "_launchURL" and reuse it

2024-07-23 09:22 UTC, NabunyaLilian commented on lib/features/user_profile/presentation/widget/buildTop.dart
what is "topDist", use names that are easy to understand

2024-07-26 06:46 UTC, trishaagaba commented
Ready for merge

2024-07-26 06:53 UTC, NabunyaLilian approved these changes
LGTM, good work Trisha

2024-07-26 06:53 UTC, merged