Document the Readme file
trishaagaba/Github-User-App pull request #5
Opened 2024-07-31 22:49 UTC by trishaagaba

**What does this PR do**
-document the ReadMe

**Tasks to be done**
-adds screenshots of the application
-describe the main features of the app

2024-08-06 14:36 UTC, NabunyaLilian requested changes

2024-08-06 14:36 UTC, NabunyaLilian commented on README.md
No need to add this; - Any other dependencies such as;
    * http: ^1.2.1
    * provider: ^6.1.2
    * share: ^2.0.4
    * json_annotation: ^4.9.0
    * url_launcher: ^6.3.0
    * infinite_scroll_pagination: ^4.0.0
    * connectivity_plus : ^2.3.0
    * shared_preferences : ^2.0.9
    * device_info_plus: ^9.0.0
    * android_intent_plus: ^3.0.1

2024-08-07 20:33 UTC, jcmugabi reviewed
change the flutter icon to a custom one

2024-08-08 09:46 UTC, NabunyaLilian approved these changes
LGTM, good work

2024-08-08 09:47 UTC, merged